let c = document.getElementById("myCanvas");
let earth = c.getContext("2d");
let pole = c.getContext('2d');
let Northline = c.getContext('2d');
let Southline = c.getContext('2d');
let Equator = c.getContext('2d');
function update(){
    if(choose_season==0) {
        earth.beginPath();
        earth.arc(150, 150, 100 ,0, 2*Math.PI, false);
        earth.strokeStyle = "white";
        earth.lineWidth = 2;
        earth.stroke();
        pole.beginPath();
        pole.lineWidth = 2;
        pole.strokeStyle = "white";
        pole.moveTo(150,0);
        pole.lineTo(150,300);
        pole.stroke();
        Northline.beginPath();
        Northline.lineWidth = 2;
        Northline.strokeStyle = "white";
        Northline.moveTo(57, 110);
        Northline.lineTo(243, 110);
        Northline.stroke();
        Equator.beginPath();
        Equator.lineWidth = 2;
        Equator.strokeStyle = "red";
        Equator.moveTo(50, 150);
        Equator.lineTo(250, 150);   
        Equator.stroke();
        Southline.beginPath();
        Southline.lineWidth = 2;
        Southline.strokeStyle = "white";
        Southline.moveTo(57, 190);
        Southline.lineTo(243, 190);
        Southline.stroke();
    }
    else if(choose_season==1){
        earth.beginPath();
        earth.arc(150, 150, 100 ,0, 2*Math.PI, false);
        earth.strokeStyle = "white";
        earth.lineWidth = 2;
        earth.stroke();
        pole.beginPath();
        pole.lineWidth = 2;
        pole.strokeStyle = "white";
        pole.moveTo(150,0);
        pole.lineTo(150,300);
        pole.stroke();
        Northline.beginPath();
        Northline.lineWidth = 2;
        Northline.strokeStyle = "red";
        Northline.moveTo(57, 110);
        Northline.lineTo(243, 110);
        Northline.stroke();
        Equator.beginPath();
        Equator.lineWidth = 2;
        Equator.strokeStyle = "white";
        Equator.moveTo(50, 150);
        Equator.lineTo(250, 150);   
        Equator.stroke();
        Southline.beginPath();
        Southline.lineWidth = 2;
        Southline.strokeStyle = "white";
        Southline.moveTo(57, 190);
        Southline.lineTo(243, 190);
        Southline.stroke();
    }
    else if(choose_season==2){
        earth.beginPath();
        earth.arc(150, 150, 100 ,0, 2*Math.PI, false);
        earth.strokeStyle = "white";
        earth.lineWidth = 2;
        earth.stroke();
        pole.beginPath();
        pole.lineWidth = 2;
        pole.strokeStyle = "white";
        pole.moveTo(150,0);
        pole.lineTo(150,300);
        pole.stroke();
        Northline.beginPath();
        Northline.lineWidth = 2;
        Northline.strokeStyle = "white";
        Northline.moveTo(57, 110);
        Northline.lineTo(243, 110);
        Northline.stroke();
        Equator.beginPath();
        Equator.lineWidth = 2;
        Equator.strokeStyle = "white";
        Equator.moveTo(50, 150);
        Equator.lineTo(250, 150);   
        Equator.stroke();
        Southline.beginPath();
        Southline.lineWidth = 2;
        Southline.strokeStyle = "red";
        Southline.moveTo(57, 190);
        Southline.lineTo(243, 190);
        Southline.stroke();
    }
}
